name: Continuous Deployment

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'main.py' # Only run if main.py or other relevant files change
      - 'requirements.txt'
      - 'hotel.csv' # If data changes and model retrains
      - '.github/workflows/ci.yml' # If CI changes, re-evaluate CD
      - '.github/workflows/cd.yml' # If CD workflow itself changes

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: Production # Optional: for environment-specific secrets/variables

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN has permission to push to GHCR

    - name: Extract metadata for Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }} # ghcr.io/your_github_username/your_repo_name
        tags: |
          type=sha,prefix=,suffix=,enable=${{ github.ref == 'refs/heads/main' }} # Use commit SHA for main branch
          type=latest,enable=${{ github.ref == 'refs/heads/main' }} # Use 'latest' tag for main branch

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
       

  
